const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("CrosshairAPI", {
    update(settings) { ipcRenderer.send("crosshair:update", settings); },
    updateOffset(x, y) { ipcRenderer.send("crosshair:updateOffset", { offset_x: x, offset_y: y }); },
    receive(callback) { ipcRenderer.on("crosshair:update", (_, data) => { callback(data); }); },
    onOffsetUpdate(callback) { ipcRenderer.on("crosshair:updateOffset", (_, data) => { callback(data); }); },
    onToggleRGB(callback) { ipcRenderer.on("toggle-rgb", () => { callback(); }); },
    saveSettings(settings) { return ipcRenderer.invoke("settings:save", settings); },
    loadSettings() { return ipcRenderer.invoke("settings:load"); },
    saveProfile(name, data) { return ipcRenderer.invoke("profile:save", { name, data }); },
    loadProfile(name) { return ipcRenderer.invoke("profile:load", name); },
    getProfiles() { return ipcRenderer.invoke("profile:list"); },
    deleteProfile(name) { return ipcRenderer.invoke("profile:delete", name); },
    renameProfile(oldName, newName) { return ipcRenderer.invoke("profile:rename", oldName, newName); },
    exportProfile(data) { return ipcRenderer.invoke("profile:export", data); },
    importProfile() { return ipcRenderer.invoke("profile:import"); },
    getDisplays() { return ipcRenderer.invoke("displays:list"); },
    recreateOverlay(index) { return ipcRenderer.invoke("overlay:recreate", index); },
    resetSettings() { return ipcRenderer.invoke("settings:reset"); },
    getConfig() { return ipcRenderer.invoke("config:get"); },
    updateConfig(updates) { return ipcRenderer.invoke("config:update", updates); },
    updateShortcut(key, value) { return ipcRenderer.invoke("shortcut:update", key, value); },
    getAutoLaunch() { return ipcRenderer.invoke("auto-launch:get"); },
    setAutoLaunch(enabled) { return ipcRenderer.invoke("auto-launch:set", enabled); },
    toggleFps() { ipcRenderer.send("fps:toggle"); },
    onFpsToggle(callback) { ipcRenderer.on("fps:toggle", () => { callback(); }); },
    setLanguage(lang) { return ipcRenderer.invoke("language:set", lang); },
    getLanguage() { return ipcRenderer.invoke("language:get"); },
    getTranslations(lang) { return ipcRenderer.invoke("language:translations", lang); },
    onGameDetected(callback) { ipcRenderer.on("game:detected", (_, game) => { callback(game); }); },
    getDetectedGame() { return ipcRenderer.invoke("game:detected"); },
    saveCustomPreset(name, data) { return ipcRenderer.invoke("custom-preset:save", name, data); },
    getCustomPresets() { return ipcRenderer.invoke("custom-preset:list"); },
    deleteCustomPreset(id) { return ipcRenderer.invoke("custom-preset:delete", id); },
    toggleFavoritePreset(id) { return ipcRenderer.invoke("custom-preset:favorite", id); },
    addHistory(data) { ipcRenderer.send("history:add", data); },
    getHistory() { return ipcRenderer.invoke("history:list"); },
    getShareLink(data) { return ipcRenderer.invoke("share:link", data); },
    loadFromShare(code) { return ipcRenderer.invoke("share:load", code); },
    checkUpdate() { return ipcRenderer.invoke("update:check"); },
    checkAutoUpdate() { return ipcRenderer.invoke("update:checkAuto"); },
    installUpdate() { return ipcRenderer.invoke("update:install"); },
    onUpdateAvailable(callback) { ipcRenderer.on("update:available", (_, v) => { callback(v); }); },
    onUpdateProgress(callback) { ipcRenderer.on("update:progress", (_, p) => { callback(p); }); },
    onUpdateDownloaded(callback) { ipcRenderer.on("update:downloaded", () => { callback(); }); },
    assignGameProfile(game, name) { ipcRenderer.send("game:assign", { game, name }); },
    resetGameAssignment(game) { ipcRenderer.send("game:reset", game); },
    onGameProfileActive(callback) { ipcRenderer.on("game:profile-active", (_, data) => { callback(data); }); },
    onCursorSet(callback) { ipcRenderer.on("cursor:set", (_, visible) => { callback(visible); }); }
});